version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # Next.js 14+ SSR uses .next regardless of SSR or SSG
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*