version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:14
    container_name: shirogane-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shirogane_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shirogane-network

  # バックエンドサービス
  backend:
    build:
      context: ./backend
    container_name: shirogane-backend
    depends_on:
      - postgres
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/shirogane_db
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8080:8080"
    networks:
      - shirogane-network

# ボリューム定義
volumes:
  postgres-data:
    driver: local

# ネットワーク定義
networks:
  shirogane-network:
    driver: bridge