services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb'
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      JAVA_OPTS: '-Xms128m -Xmx256m'
