version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  
  pre_build:
    commands:
      - echo Database migration started on `date`
      - echo Retrieving database credentials from Secrets Manager
      - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_ARN --query SecretString --output text)
      - export DB_USER=$(echo "$SECRET_VALUE" | jq -r .username)
      - export DB_PASSWORD=$(echo "$SECRET_VALUE" | jq -r .password)
      - echo Database migration starting for $ENVIRONMENT environment
      - echo "DB_HOST=$DB_HOST"
      - echo "DB_NAME=$DB_NAME"
      - echo "DB_USER=$DB_USER"
  
  build:
    commands:
      - pwd
      - ls -la
      - ls -la ..
      - cd backend
      - echo Running Liquibase migration
      - ./gradlew liquibaseUpdate
      - echo Migration completed successfully
  
  post_build:
    commands:
      - echo Database migration completed on `date` for $ENVIRONMENT environment