spring:
  config:
    activate:
      on-profile: lambda
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcDataAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcRepositoriesAutoConfiguration
  main:
    web-application-type: reactive
  flyway:
    enabled: false

# Lambda関数設定
spring.cloud.function:
  web:
    export:
      enabled: true
      auto-registration: true
      path-pattern: /**

# ロギング設定
logging:
  level:
    root: INFO
    com.shirogane.holy.knights: DEBUG
    org.springframework.cloud.function: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG