spring:
  config:
    activate:
      on-profile: lambda
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:shirogane}
    username: ${DATABASE_USERNAME:postgres}  
    password: ${DATABASE_PASSWORD:postgres}
    pool:
      initial-size: 1
      max-size: 3
      max-idle-time: 10s
      max-acquire-time: 30s
      max-create-connection-time: 30s
      validation-query: SELECT 1
  flyway:
    enabled: false

# Lambda関数設定
spring.cloud.function:
  web:
    export:
      enabled: true
      auto-registration: true
      path-pattern: /**

# ロギング設定
logging:
  level:
    root: INFO
    com.shirogane.holy.knights: DEBUG
    org.springframework.cloud.function: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG