server:
  port: 8080
  
spring:
  application:
    name: shirogane-holy-knights-api
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:shirogane_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  flyway:
    enabled: false
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  webflux:
    cors:
      allowed-origins: "http://localhost:*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# アクチュエーターの設定
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
    
  
# ロギング設定
logging:
  level:
    root: INFO
    com.shirogane.holy.knights: INFO
    org.springframework.web: INFO
    
# Spring Cloud Function設定
spring.cloud.function:
  definition: ""
  scan:
    packages: "com.shirogane.holy.knights"
  web:
    export:
      enabled: true

# AWS Lambda関連設定
aws:
  lambda:
    function:
      handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker