server:
  port: 8080
  
spring:
  application:
    name: shirogane-holy-knights-api
  main:
    web-application-type: reactive
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/shirogane_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${JDBC_DATABASE_MAX_POOL_SIZE:3}
      auto-commit: false
      transaction-isolation: TRANSACTION_REPEATABLE_READ
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# アクチュエーターの設定
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
    
# CORS設定
cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Content-Type,Authorization
  
# ロギング設定
logging:
  level:
    root: INFO
    com.shirogane.holy.knights: INFO
    org.springframework.web: INFO
    
# Spring Cloud Function設定
spring.cloud.function:
  definition: archiveSearch
  scan:
    packages: com.shirogane.holy.knights.infrastructure.lambda.functions
  web:
    export:
      enabled: true
      auto-registration: true
      path-pattern: /**
  url-handler-enabled: true

# AWS Lambda関連設定
aws:
  lambda:
    function:
      handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker