spring:
  config:
    activate:
      on-profile: lambda-local
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shirogane
    username: postgres
    password: postgres
    pool:
      initial-size: 1
      max-size: 3
      max-idle-time: 10s
      max-acquire-time: 30s
      max-create-connection-time: 30s
      validation-query: SELECT 1

server:
  port: 8080

logging:
  level:
    root: INFO
    com.shirogane.holy.knights: DEBUG
    org.springframework.cloud.function: DEBUG
    org.springframework.cloud.function.web.mvc: TRACE
    org.springframework.web.servlet.handler: TRACE

# Spring Cloud Function設定
spring.cloud.function:
  definition: videoSearch
  scan:
    packages: com.shirogane.holy.knights.infrastructure.lambda.functions
  web:
    export:
      enabled: true
      auto-registration: true
      path-pattern: /**
  url-handler-enabled: true
      
# CORS設定
cors:
  allowed-origins: http://localhost:*
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Content-Type,Authorization,Content-Length,X-Requested-With,Accept,*