name: Frontend Test and Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-test.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint || true

    - name: Run type check
      run: npm run type-check || npx tsc --noEmit

    - name: Run tests
      run: npm test -- --passWithNoTests
      env:
        CI: true

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.API_ENDPOINT || 'http://localhost:3001' }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: matrix.node-version == '20.x'
      with:
        name: frontend-build
        path: |
          frontend/.next
          frontend/public
        retention-days: 7

    - name: Check bundle size
      if: matrix.node-version == '20.x'
      run: |
        echo "### Bundle Size Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        find .next -name "*.js" -not -path "*/node_modules/*" | while read file; do
          size=$(du -h "$file" | cut -f1)
          echo "- \`${file#.next/}\`: $size" >> $GITHUB_STEP_SUMMARY
        done